import {
  ArrowDownRight,
  ArrowUpRight,
  Info,
  Minus,
  Sparkles,
} from "lucide-react";

import { Card } from "@/components/ui/card";
import { SignalBadge } from "@/components/common/signal-badge";
import type { Outlook } from "@/lib/markets/outlook";
import { cn } from "@/lib/utils";

function FactorRow({
  text,
  direction,
}: {
  text: string;
  direction: "up" | "down" | "neutral";
}) {
  const Icon =
    direction === "up"
      ? ArrowUpRight
      : direction === "down"
        ? ArrowDownRight
        : Minus;
  const color =
    direction === "up"
      ? "text-[var(--pos)]"
      : direction === "down"
        ? "text-[var(--neg)]"
        : "text-[var(--neutral)]";
  const label =
    direction === "up"
      ? "pushing up"
      : direction === "down"
        ? "pushing down"
        : "neutral";
  return (
    <li className="flex items-start gap-2.5 py-2">
      <Icon
        className={cn("mt-0.5 size-4 shrink-0", color)}
        strokeWidth={2.5}
      />
      <div className="min-w-0">
        <p className="text-foreground text-sm leading-snug">{text}</p>
        <span className={cn("text-[10px] font-medium uppercase", color)}>
          {label}
        </span>
      </div>
    </li>
  );
}

export function OutlookCard({ outlook }: { outlook: Outlook | null }) {
  if (!outlook) {
    return (
      <Card className="flex flex-col p-5 md:col-span-1">
        <div className="flex items-center gap-2">
          <Sparkles className="size-4 text-[var(--accent)]" />
          <span className="text-text-tertiary text-[11px] font-medium tracking-wide uppercase">
            Sell / Hold Outlook
          </span>
        </div>
        <p className="text-text-secondary mt-4 text-sm leading-relaxed">
          The market read is generated by Claude from the futures trend and a
          news feed. Set{" "}
          <span className="text-foreground font-mono text-xs">
            ANTHROPIC_API_KEY
          </span>{" "}
          to enable it.
        </p>
      </Card>
    );
  }

  return (
    <Card className="flex flex-col p-5 md:col-span-1">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Sparkles className="size-4 text-[var(--accent)]" />
          <span className="text-text-tertiary text-[11px] font-medium tracking-wide uppercase">
            Sell / Hold Outlook
          </span>
        </div>
        <SignalBadge signal={outlook.signal} />
      </div>

      <p className="text-text-secondary mt-4 text-sm leading-relaxed">
        {outlook.summary}
      </p>

      <ul className="divide-border/60 mt-3 divide-y border-t border-border/60">
        {outlook.factors.map((f, i) => (
          <FactorRow key={i} text={f.text} direction={f.direction} />
        ))}
      </ul>

      <div className="mt-3 flex items-start gap-2 rounded-md border border-border/70 bg-bg-elevated/40 px-3 py-2">
        <Info className="text-text-tertiary mt-0.5 size-3.5 shrink-0" />
        <p className="text-text-tertiary text-[11px] leading-relaxed">
          {outlook.disclaimer}
        </p>
      </div>

      <div className="text-text-tertiary mt-3 flex flex-wrap items-center gap-x-2 gap-y-1 text-[10px]">
        {outlook.trendNote && <span className="tnum">{outlook.trendNote}</span>}
        {outlook.trendNote && <span>·</span>}
        <span>news: placeholder feed</span>
        <span>·</span>
        <span className="font-mono">{outlook.model}</span>
      </div>
    </Card>
  );
}
